[project]
name = "mcp-server"
version = "0.1.0"
description = "Weather MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
